### ISSUE TITLE
Splitterpane Dimensions

### ISSUE THREAD

**Issue by gle4711** [jsakamoto/Toolbelt.Blazor.SplitContainer#5]
Hello,
the event "FirstPaneSizeChanged" gives me the height or width of the 1st splitter panel. How can I get the width or height of the associated 2nd splitter panel.

Kind regards 
Erich

**Comment by jsakamoto** [comment]
@gle4711 Unfortunately, the SplitterContainer component doesn't provide the ability to report the width or height information of the rest pane. Because it is complicated to implement it. In usual cases, the size of the rest pane can be changed by not only users dragging the splitter bar inside the SplitterContainer component but also changing the size of the browser window. Capturing all of those frequent size-changing events and handling them in Blazor apps have many tough consideration points of the architectures. So I would not provide such an ability on the SplitterContainer component. If you have to manage to get the size of the rest pane, you may be able to do it with the JavaScript interop. If you hope, please ask somebody else somewhere, such as StackOverflow.com.
